name: Update players data

on:
  schedule:
    - cron: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *'
  workflow_dispatch:

# Даём права на запись
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch data from Google Sheets
        run: |
          curl -L -o data/players.json "https://script.google.com/macros/s/AKfycbxo-EHKV_-AneAKpA8BOx_aQ0_icKS42Ad7-6Qy_B_O6KVSqdMYJJxDYjgOBcp4VZLdcA/exec"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/players.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update players data"
          git push
